### ISSUE TITLE
ERROR: failed to sync instances when issuing `scontrol reboot`

### ISSUE THREAD

**Issue by jadams-accenture** [GoogleCloudPlatform/hpc-toolkit#2139]
**If you find a similar existing issue, please comment on that issue instead of creating a new one.**

**If you are submitting a feature request, please start a [discussion](https://github.com/GoogleCloudPlatform/hpc-toolkit/discussions/new?category=ideas-and-feature-requests) instead of creating an issue.**

### Describe the bug

After issuing a reboot command to a node via scontrol, e.g. sudo scontrol reboot ASAP <a_cluster_node>

the following error begins appearing in the slurmsync.log:

```
ERROR: failed to sync instances
Traceback (most recent call last):
  File "/slurm/scripts/slurmsync.py", line 322, in main
    sync_slurm()
  File "/slurm/scripts/slurmsync.py", line 203, in sync_slurm
    for name, state in lkp.slurm_nodes().items()
  File "/slurm/scripts/util.py", line 1330, in slurm_nodes
    nodes = {
  File "/slurm/scripts/util.py", line 1330, in <dictcomp>
    nodes = {
  File "/slurm/scripts/util.py", line 1319, in make_node_tuple
    node, fullstate = node_line.split(",")
ValueError: not enough values to unpack (expected 2, got 1)
```

### Steps to reproduce

1. sudo scontrol reboot ASAP <a_cluster_node>

### Expected behavior

No erroroccurs

### Actual behavior

In /var/log/slurm/slurmsync.log, the following is logged:

```
ERROR: failed to sync instances
Traceback (most recent call last):
  File "/slurm/scripts/slurmsync.py", line 322, in main
    sync_slurm()
  File "/slurm/scripts/slurmsync.py", line 203, in sync_slurm
    for name, state in lkp.slurm_nodes().items()
  File "/slurm/scripts/util.py", line 1330, in slurm_nodes
    nodes = {
  File "/slurm/scripts/util.py", line 1330, in <dictcomp>
    nodes = {
  File "/slurm/scripts/util.py", line 1319, in make_node_tuple
    node, fullstate = node_line.split(",")
ValueError: not enough values to unpack (expected 2, got 1)
```

### Blueprint

If applicable, attach or paste the blueprint YAML used to produce the bug.

```yaml

```

### Expanded Blueprint

If applicable, please attach or paste the expanded blueprint. The expanded blueprint can be obtained by running `ghpc expand your-blueprint.yaml`.

Disregard if the bug occurs when running `ghpc expand ...` as well.

```yaml

```

### Output and logs

```text

```

### Execution environment

- OS: [macOS, ubuntu, ...]
- Shell (To find this, run `ps -p $$`): [bash, zsh, ...]
- go version:

### Additional context

When a reboot is issued, an extra line in the node state is present: 

NextState=RESUME

The regex on line 1326 of util.py is too permissive, and also matches this additional line, breaking the subsequent node output. Adding a leading whitespace pattern to the State pattern appears to resolve the issue.  e.g.

r"grep -oP '^NodeName=\K(\S+)|\s+State=\K(\S+)' | "

**Comment by rohitramu** [comment]
Thanks for raising this issue!  Could you please share a blueprint which reproduces the issue?

**Comment by mr0re1** [comment]
Could you please provide output of?:
```sh
sudo scontrol show nodes
```
and 
```sh
sudo scontrol show nodes | grep -oP '^NodeName=\K(\S+)|State=\K(\S+)' |  paste -sd',\n'
```

**Comment by jadams-accenture** [comment]
Hello!

I'm not sure I can share the blueprint here, but I may be able to share any specific details that might be relevant.

I've patched the cluster, so all the commands currently work as expected, but do have a sanitized capture of the output when chasing this down:

```
my-fake-cluster-ghpc-0,=DOWN+CLOUD+DRAIN+NOT_RESPONDING
my-fake-cluster-ghpc-1,=MIXED+CLOUD
my-fake-cluster-ghpc-2,=DOWN+CLOUD+DRAIN+NOT_RESPONDING
my-fake-cluster-ghpc-3,=MIXED+CLOUD
my-fake-cluster-ghpc-4,=ALLOCATED+CLOUD
my-fake-cluster-ghpc-5,=ALLOCATED+CLOUD
my-fake-cluster-ghpc-6,=ALLOCATED+CLOUD
my-fake-cluster-ghpc-7,=ALLOCATED+CLOUD
my-fake-cluster-ghpc-8,=ALLOCATED+CLOUD
my-fake-cluster-ghpc-9,=ALLOCATED+CLOUD
my-fake-cluster-ghpc-10,=ALLOCATED+CLOUD
my-fake-cluster-ghpc-11,=MIXED+CLOUD+DRAIN+REBOOT_REQUESTED
=RESUME,my-fake-cluster-ghpc-12
=ALLOCATED+CLOUD,my-fake-cluster-ghpc-13
=ALLOCATED+CLOUD,my-fake-cluster-ghpc-14
=ALLOCATED+CLOUD,my-fake-cluster-ghpc-15
=ALLOCATED+CLOUD,my-fake-cluster-ghpc-16
=ALLOCATED+CLOUD,my-fake-cluster-ghpc-17
=ALLOCATED+CLOUD,my-fake-cluster-ghpc-18
=ALLOCATED+CLOUD,my-fake-cluster-ghpc-19
=ALLOCATED+CLOUD,my-fake-cluster-ghpc-20
=ALLOCATED+CLOUD,my-fake-cluster-ghpc-21
=ALLOCATED+CLOUD,my-fake-cluster-ghpc-22
=ALLOCATED+CLOUD,my-fake-cluster-ghpc-23
=MIXED+CLOUD,my-fake-cluster-ghpc-24
=IDLE+CLOUD,my-fake-cluster-ghpc-25
=IDLE+CLOUD,my-fake-cluster-ghpc-26
=IDLE+CLOUD,my-fake-cluster-ghpc-27
=IDLE+CLOUD,my-fake-cluster-ghpc-28
=IDLE+CLOUD,my-fake-cluster-ghpc-29
=IDLE+CLOUD,my-fake-cluster-ghpc-30
=IDLE+CLOUD,my-fake-cluster-ghpc-31
=ALLOCATED+CLOUD,my-fake-cluster-ghpc-32
=MIXED+CLOUD,my-fake-cluster-ghpc-33
=ALLOCATED+CLOUD,my-fake-cluster-ghpc-34
=MIXED+CLOUD,my-fake-cluster-ghpc-35
=ALLOCATED+CLOUD,my-fake-cluster-ghpc-36
=ALLOCATED+CLOUD,my-fake-cluster-ghpc-37
=IDLE+CLOUD,my-fake-cluster-ghpc-38
=IDLE+CLOUD,my-fake-cluster-ghpc-39
=IDLE+CLOUD,my-fake-cluster-ghpc-40
=IDLE+CLOUD,my-fake-cluster-ghpc-41
=MIXED+CLOUD,my-fake-cluster-ghpc-42
=IDLE+CLOUD,my-fake-cluster-ghpc-43
=IDLE+CLOUD,my-fake-cluster-ghpc-44
=IDLE+CLOUD,my-fake-cluster-ghpc-45
=IDLE+CLOUD,my-fake-cluster-ghpc-46
=IDLE+CLOUD,my-fake-cluster-ghpc-47
=IDLE+CLOUD,my-fake-cluster-ghpc-48
=IDLE+CLOUD,my-fake-cluster-ghpc-49
=IDLE+CLOUD,my-fake-cluster-ghpc-50
=ALLOCATED+CLOUD,my-fake-cluster-ghpc-51
=MIXED+CLOUD,my-fake-cluster-ghpc-52
=ALLOCATED+CLOUD,my-fake-cluster-ghpc-53
=ALLOCATED+CLOUD,my-fake-cluster-ghpc-54
=ALLOCATED+CLOUD,my-fake-cluster-ghpc-55
=ALLOCATED+CLOUD,my-fake-cluster-ghpc-56
=ALLOCATED+CLOUD,my-fake-cluster-ghpc-57
=IDLE+CLOUD,my-fake-cluster-ghpc-58
=MIXED+CLOUD,my-fake-cluster-ghpc-59
=IDLE+CLOUD,my-fake-cluster-ghpc-60
=IDLE+CLOUD,my-fake-cluster-ghpc-61
=IDLE+CLOUD,my-fake-cluster-ghpc-62
=IDLE+CLOUD,my-fake-cluster-ghpc-63
```
